# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install dependencies
      run:
          sudo apt install elinks gzip
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'src'
        extensions: 'h,cpp,cc,hxx,hpp'
        clangFormatVersion: 9
        style: Google
    # Install latest CMake.
    - uses: lukka/get-cmake@latest

    - name: Set vcpkg's response file path used as part of cache's key.
      uses: lukka/set-shell-env@master
      with:
          VCPKGRESPONSEFILE: ${{ github.workspace }}/vcpkg.txt

    - name: Restore from cache and run vcpkg
      uses: lukka/run-vcpkg@v3
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'
        appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}

    - name: Build stdman
      uses: lukka/run-cmake@v2
      with:
        useVcpkgToolchainFile: true
        cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
        cmakeGenerator: UnixMakefiles
        buildDirectory: '${{runner.workspace}}/_build'
        cmakeBuildType: Release

    - name: Generate
      working-directory: '${{runner.workspace}}/_build'
      run: |
        sudo apt install tree
        make generate
        sudo make install > /dev/null
        mandb
        man std::string
